version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: background_jobs_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: background_jobs_local
    ports:
      - "5433:5432"
    # no volumes needed